[[ if .PrivateNetworkAccess ]]
# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: ops.dac.nokia.com/v1alpha1
kind: PrivateNetworkAccess
metadata:
  name: private-network-for-sml-evo
spec:
  [[- if .PrivateNetworkAccess.AppPodFixIp ]]
  appPodFixIp: 
    statefulsets.apps/sml-evo: [[ .PrivateNetworkAccess.AppPodFixIp ]]
  [[- end ]]
  customerNetwork: [[ .PrivateNetworkAccess.ApplicationNetwork ]]
  networks:
  [[- range $net := .PrivateNetworkAccess.Networks]]
  - apnUUID: [[ $net.ApnUUID ]]
  [[- if $net.AdditionalRoutes ]]
    additionalRoutes:
    [[- range $net.AdditionalRoutes ]]
    - [[ . ]]
    [[- end ]]
  [[- end ]]
  [[- end ]]
[[ end ]]
