# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: global-operators
spec:
  targetNamespaces:
  - sml-evo-system
