# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# Default values for example-consul.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  [[- if .Ports ]]
  uiport: [[ or .Ports.UiPort 9000 ]]
  udpportrangelow : [[ or .Ports.UdpPortRangeLow 15000 ]]
  udpportrangehigh : [[ or .Ports.UdpPortRangeHigh 49000 ]]
  [[- else ]]
  uiport: 9000
  udpportrangelow : 15000
  udpportrangehigh : 49000
  [[- end ]]
  [[- if and (.PrivateNetworkAccess) (ne .PrivateNetworkAccess.AppPodFixIp "") ]]
  bindaddress: [[ .PrivateNetworkAccess.AppPodFixIp ]]
  [[- end ]]
[[- if and (.Domain) (ne .Domain.Name "") ]]
domain:
  name: [[ .Domain.Name ]]
  [[- if and (.Domain.NetworkId) (ne .Domain.NetworkId "") ]]
  networkId: [[ .Domain.NetworkId ]]
  [[- end ]]
[[- end ]]
