# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# Default values for example-consul.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metricsDomainName: [[ .MetricsDomainName ]]
service:
  uiport: [[ .Ports.UiPort ]]
  udpportrangelow : [[ .Ports.UdpPortRangeLow ]]
  udpportrangehigh : [[ .Ports.UdpPortRangeLow ]]
  bindaddress: [[ .PrivateNetworkAccess.AppPodFixIp  ]]
[[- if and (.Domain) (ne .Domain.Name "") ]]
domain:
  name: [[ .Domain.Name ]]
  [[- if and (.Domain.NetworkId) (ne .Domain.NetworkId "") ]]
  networkId: [[ .Domain.NetworkId ]]
  [[- end ]]
[[- end ]]
