
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: app-ns-placeholder
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dac.nokia.com
  resources:
  - smlevoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dac.nokia.com
  resources:
  - smlevoes/finalizers
  verbs:
  - update
- apiGroups:
  - app.dac.nokia.com
  resources:
  - smlevoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dnsentry.dac.nokia.com
  resources:
  - dnsentries
  verbs:
  - '*'
- apiGroups:
  - ops.dac.nokia.com
  resources:
  - hostconfigs
  - licenceexpireds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
