
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dac.nokia.com.example.com
  resources:
  - smlevoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dac.nokia.com.example.com
  resources:
  - smlevoes/finalizers
  verbs:
  - update
- apiGroups:
  - app.dac.nokia.com.example.com
  resources:
  - smlevoes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ops.dac.nokia.com
  resources:
  - licenceexpireds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
