# permissions for end users to edit smlevoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smlevo-editor-role
rules:
- apiGroups:
  - app.dac.nokia.com.example.com
  resources:
  - smlevoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.dac.nokia.com.example.com
  resources:
  - smlevoes/status
  verbs:
  - get
