# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    application-constraints: |
      storage-service:
        requests:
        - name: storage-persvol-1
          size: 500Mi
  name: sml-evo.v0.0.1
  namespace: operators
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: SmlEvo
      name: smlevoes.app.dac.nokia.com.example.com
      version: v1alpha1
      displayName: SML EVO
      description: SML EVO
  description: Placeholder description
  displayName: SML EVO
  install:
    spec:
      deployments:
      - name: sml-evo-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: sml-evo-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: sml-evo-operator
            spec:
              containers:
              - command:
                - sml-evo-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: sml-evo-operator
                - name: DEPLOYMENT_DIR
                  value: /usr/src/app
                - name: RESREQ_DIR
                  value: /usr/src/app/resource-reqs-generated
                image: localhost:32000/sml-evo-operator:0.0.0.62
                imagePullPolicy: Always
                name: sml-evo-operator
                resources: {}
              serviceAccountName: sml-evo-controller-manager
              imagePullSecrets:
                - name: pull-secret
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - sml-evo-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - app.dac.nokia.com
          resources:
          - '*'
          - sml-evos
          verbs:
          - '*'
        - apiGroups:
            - ops.dac.nokia.com
          resources:
            - '*'
            - sml-evos
          verbs:
            - '*'
        serviceAccountName: sml-evo-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
