apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kYWMubm9raWEuY29tIjp7InVzZXJuYW1lIjoicHVibGljYXBwIiwicGFzc3dvcmQiOiJ4VXlXUTJhRVpxZmE4WGJMIiwiZW1haWwiOiJkYWNAbm9raWEuY29tIiwiYXV0aCI6ImNIVmliR2xqWVhCd09uaFZlVmRSTW1GRlduRm1ZVGhZWWt3PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: publicapps-pullsecret
type: kubernetes.io/dockerconfigjson
