# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sml-evo
  labels:
    ndac.appfw.private-network-access: private-network-for-sml-evo
spec:
  selector:
    matchLabels:
      app: sml-evo
  updateStrategy:
    type: RollingUpdate
  serviceName: sml-evo
  replicas: {{.Values.replicaCount}}
  template:
    metadata:
      labels:
        app: sml-evo
        statusCheck: "true"
    spec:
      imagePullSecrets:
      - name: publicapps-pullsecret
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
        - name: evo-persvol
          persistentVolumeClaim:
            claimName: storage-persvol-1
      containers:
        - name: orchestrator
          image: registry.dac.nokia.com/public_apps/smartmobilelabs/evo:master-102
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 750m
              memory: 4Gi
          ports:
            - containerPort: {{.Values.service.uiport}}
              name: ui-port
            - containerPort: {{.Values.service.udpportrangelow}}
              name: portrangemin
            - containerPort: {{.Values.service.udpportrangehigh}}
              name: portrangemax
          volumeMounts:
            - mountPath: /persvol
              name: evo-persvol
          env:
            - name: COMPOSER_BIND_ADDRESS
              value: {{ .Values.service.bindaddress }}
